config/routes.rb
Rails.application.routes.draw do
  resources :weapons
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'weapons#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :weapons
  has_many :subgenres
end

app/models/subgenre.rb
class Subgenre < ApplicationRecord
  has_many :weapons
  belongs_to :genre
end

app/models/weapon.rb
class Weapon < ApplicationRecord
    has_many :genres
    has_many :subgenres
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: [:show, :edit, :update, :destroy]

  # GET /weapons
  # GET /weapons.json
  def index
    @weapons = Weapon.all
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
  end

  # GET /weapons/new
  def new
    @weapon = Weapon.new
  end

  # GET /weapons/1/edit
  def edit
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(weapon_params)

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render :show, status: :created, location: @weapon }
      else
        format.html { render :new }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weapons/1
  # PATCH/PUT /weapons/1.json
  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { render :show, status: :ok, location: @weapon }
      else
        format.html { render :edit }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon.destroy
    respond_to do |format|
      format.html { redirect_to weapons_url, notice: 'Weapon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weapon_params
      params.require(:weapon).permit(:title, :body, :image_url, :skill)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiSouls</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">WikiSouls</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
          <a class='nav-link' href='#'></a>
        </li>
    </ul>
  </div>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      
      <li class='nav-item'>
        Logged in as '"00\\||//00"'
      </li>
      
    </div>
  </div>
</nav>

<div class='container'>
  <div class='row'>
    <div class='col-lg-10'>

      <%= yield %>

    </div>
    <div class='col-lg-2'>
      <ul class='nav nav-pills flex-column'>
        <li class='nav-item'><%= link_to 'All Weapons', root_path, class: 'nav-link' %></li>

        <% Genre.all.each do |genre| %>

        <li class='nav-item'>
          <a class="nav-link" href="<%= weapons_path(genre: genre.title) %>" >
            <%= genre.title %>
          </a>
        
        <% end %>

        </li>
    </div>
  </div>
</div>

  </body>
</html>

app/views/weapons/_form.html.erb
<%= form_with(model: weapon, local: true) do |form| %>
  <% if weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
      <% weapon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title %>
  </div>

  <div class="form-group">
    <%= form.text_area :body %>
  </div>

  <div class="form-group">
    <%= form.text_field :image_url %>
  </div>

  <div class="form-group">
    <%= form.text_field :skill %>
  </div>

  <div class='c-select'>
    <%= form.collection_select :genre_id, Genre.all, :id, :title, {prompt: 'Choose a Weapon Genre'}, class: 'form-control' %>
  </div>

  <div class='c-select'>
    <%= form.collection_select :subgenre_id, Subgenre.all, :id, :title, {prompt: 'Choose a Weapon Subgenre'}, class: 'form-control' %>
  </div>

  <div class="form group">
    <%= form.submit 'Submit', class: 'btn btn-default btn-primary' %>
  </div>
<% end %>

app/views/weapons/edit.html.erb
<h1>Editing Weapon</h1>

<%= render 'form', weapon: @weapon %>

<%= link_to 'Show', @weapon %> |
<%= link_to 'Back', weapons_path %>

app/views/weapons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Weapons</h1>

<div class='jumbotron'>
  <% @weapons.each do |weapon| %>
  <br>
  <h2>
    <%= weapon.title %>
  </h2>
  <h5>
    <%= link_to 'Read More', weapon_path(weapon) %>
  </h5>
  <h5>
    <%= truncate(weapon.body, length: 200) %>
  </h5>
  <br>
  <% end %>
</div>

app/views/weapons/new.html.erb
<h1>New Weapon</h1>

<%= render 'form', weapon: @weapon %>

<%= link_to 'Back', weapons_path %>

app/views/weapons/show.html.erb
<p id="notice"><%= notice %></p>

<div class='jumbotron'>
  <p id="notice"><%= notice %></p>
  <div class='row'>
    <div class='col-lg-7'>
      <h1>
        <%= @weapon.title %>
      </h1>
      <p>
        <strong>Description:</strong><br> <%= @weapon.body %><br>
        <strong>Skill:</strong><br> <%= @weapon.skill %><br>
        <%= link_to 'Back', weapons_path %>
      </p>
    </div>
    <div class='col-lg-2'>
      <%= image_tag @weapon.image_url, :alt => @weapon.title, float: 'right' %>
    </div>
    
  </div>
</div>